openapi: 3.0.3
info:
  title: Rokwire Content Building Block API
  description: Polls Content Block API Documentation
  version: 1.2.3
servers:
  - url: 'https://api.rokwire.illinois.edu/content'
    description: Production server
  - url: 'https://api-test.rokwire.illinois.edu/content'
    description: Test server
  - url: 'https://api-dev.rokwire.illinois.edu/content'
    description: Development server
  - url: 'http://localhost/content'
    description: Local server
tags:
  - name: Admin
    description: Admin applications APIs.
  - name: Apis
    description: Apis applications APIs.
  - name: Client
    description: Client applications APIs.
paths:
  '/content/profile_photo/{user-id}':
    get:
      tags:
        - Apis
      summary: Retrieves the profile photo
      description: |
        Retrieves a reward inventory by id
      security:
        - bearerAuth: []
      parameters:
        - name: user_id
          in: path
          description: the id of the user
          required: true
          style: simple
          explode: false
          schema:
            type: string
        - name: size
          in: query
          description: 'Possible values default, medium, small'
          required: true
          style: simple
          explode: false
          schema:
            type: string
      responses:
        '200':
          description: Success
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '500':
          description: Internal error
  /content/profile_photo:
    get:
      tags:
        - Apis
      summary: Retrieves the profile photo
      description: |
        Retrieves a reward inventory by id
      security:
        - bearerAuth: []
      parameters:
        - name: size
          in: query
          description: 'Possible values default, medium, small'
          required: true
          style: simple
          explode: false
          schema:
            type: string
      responses:
        '200':
          description: Success
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '500':
          description: Internal error
    post:
      tags:
        - Apis
      summary: Stores profile photo
      description: |
        Stores profile photo
      security:
        - bearerAuth: []
      requestBody:
        description: Stores profile photo
        content:
          application/json: null
        required: true
      responses:
        '200':
          description: Success
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '500':
          description: Internal error
    delete:
      tags:
        - Apis
      summary: Deletes the profile photo of the user who request
      description: |
        Deletes the profile photo of the user who request
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Success
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '500':
          description: Internal error
  components: null
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Reward:
      type: object
      properties:
        _id:
          type: string
        category:
          type: string
        date_created:
          type: string
        date_updated:
          type: string
        data:
          type: array
        org_id:
          type: string
        app_id:
          type: string
    RewardClaim:
      type: object
      properties:
        height:
          type: integer
        width:
          type: integer
        quality:
          type: integer
