openapi: 3.0.3
info:
  title: Rokwire Content Building Block API
  description: Polls Content Block API Documentation
  version: 1.2.3
servers:
  - url: 'https://api.rokwire.illinois.edu/content'
    description: Production server
  - url: 'https://api-test.rokwire.illinois.edu/content'
    description: Test server
  - url: 'https://api-dev.rokwire.illinois.edu/content'
    description: Development server
  - url: 'http://localhost/content'
    description: Local server
tags:
  - name: Admin
    description: Admin applications APIs.
  - name: Apis
    description: Apis applications APIs.
  - name: Client
    description: Client applications APIs.
paths: null
