basePath: /content
host: localhost
info:
  contact: {}
  description: Rokwire Content Building Block API Documentation.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Rokwire Content Building Block API
  version: 0.4.0
paths:
  /student_guides:
    get:
      consumes:
      - application/json
      description: Retrieves  all items
      operationId: getAllStudentGuides
      responses:
        "200":
          description: ""
      security:
      - RokwireAuth AdminUserAuth: []
      tags:
      - StudentGuides
    post:
      consumes:
      - application/json
      description: Retrieves  all items
      operationId: CreateStudentGuide
      responses:
        "200":
          description: ""
      security:
      - AdminUserAuth: []
      tags:
      - StudentGuides
  /student_guides/{id}:
    delete:
      description: Deletes a student guide with the specified id
      operationId: DeleteStudentGuide
      responses:
        "200":
          description: ""
      security:
      - AdminUserAuth: []
      tags:
      - StudentGuides
    get:
      consumes:
      - application/json
      description: Retrieves  all items
      operationId: GetStudentGuide
      produces:
      - application/json
      responses:
        "200":
          description: ""
      security:
      - RokwireAuth AdminUserAuth: []
      tags:
      - StudentGuides
    put:
      consumes:
      - application/json
      description: Updates a student guide with the specified id
      operationId: UpdateStudentGuide
      produces:
      - application/json
      responses:
        "200":
          description: ""
      security:
      - AdminUserAuth: []
      tags:
      - StudentGuides
  /version:
    get:
      description: Gives the service version.
      operationId: Version
      produces:
      - text/plain
      responses:
        "200":
          description: ""
schemes:
- https
securityDefinitions:
  AdminGroupAuth:
    in: header
    name: GROUP
    type: apiKey
  AdminUserAuth:
    in: header (add Bearer prefix to the Authorization value)
    name: Authorization
    type: apiKey
  RokwireAuth:
    in: header
    name: ROKWIRE-API-KEY
    type: apiKey
swagger: "2.0"
