openapi: 3.0.3
info:
  title: Rokwire Content Building Block API
  description: Polls Content Block API Documentation
  version: 1.2.3
servers:  
  - url: 'https://api.rokwire.illinois.edu/content'
    description: Production server
  - url: 'https://api-test.rokwire.illinois.edu/content'
    description: Test server
  - url: 'https://api-dev.rokwire.illinois.edu/content'
    description: Development server
  - url: 'http://localhost/content'
    description: Local server
tags:
  - name: Admin
    description: Admin applications APIs.
  - name: Apis
    description: Apis applications APIs.
  - name: Client
    description: Client applications APIs.
paths:
  #Admin
  #Apis
  /content/profile_photo/{user-id}:
    $ref: "./resources/apis/profile-photo-userID.yaml"
  /content/profile_photo:
    $ref: "./resources/apis/profile-photo.yaml"   
  #Client
  /content/student_guides:
    $ref: "./resources/client/student-guides.yaml"
  /content/student_guides/{id}:
    $ref: "./resources/client/student-guidesid.yaml" 
  /content/healt_locations:
    $ref: "./resources/client/health-locations.yaml" 
  /content/health_locations/{id}:
    $ref: "./resources/client/health-locationsid.yaml"
  /content/content_items:
    $ref: "./resources/client/content-items.yaml"    
  /content/content_items/{id}:
    $ref: "./resources/client/content-itemsid.yaml" 
  /content/content_item/categories:
    $ref: "./resources/client/content-items-categories.yaml"  
  /content/image:
    $ref: "./resources/client/image.yaml"
  /content/twitter/users/{user_id}/tweets:
    $ref: "./resources/client/twitter-user-tweets.yaml"      
  
  components:
  securitySchemes:
      bearerAuth:            # arbitrary name for the security scheme
        type: http
        scheme: bearer
        bearerFormat: JWT
  schemas:
    $ref: "./schemas/index.yaml"